CREATE SEQUENCE dbid;

DROP TABLE IF EXISTS uuid;
CREATE TABLE uuid (
	uuid_dbid INTEGER NOT NULL DEFAULT NEXTVAL('dbid')  PRIMARY KEY,
	uuid_uuid VARCHAR(36) NOT NULL
) ;

DROP TABLE IF EXISTS protocol;
CREATE TABLE protocol (
	protocol_id INT DEFAULT NEXTVAL('dbid') PRIMARY KEY
	,protocol_name VARCHAR(100)
	,protocol_doc VARCHAR(100000)
	,removed BOOLEAN DEFAULT FALSE
);
CREATE TABLE PUBLIC."icd" (
	"icd_id" INTEGER NOT NULL DEFAULT (NEXT VALUE FOR PUBLIC.SYSTEM_SEQUENCE_71D10F2A_A3B6_4A5F_901E_C2CCD0E859D3) AUTO_INCREMENT,
	"icd_root" INTEGER NOT NULL,
	"icd_left_key" INTEGER NOT NULL,
	"icd_right_key" INTEGER NOT NULL,
	"icd_level" INTEGER NOT NULL,
	"icd_start" INTEGER NOT NULL,
	"icd_end" INTEGER,
	"icd_code" VARCHAR(7) NOT NULL,
	"icd_name" VARCHAR(255) NOT NULL,
	CONSTRAINT CONSTRAINT_1 PRIMARY KEY ("icd_id"),
	CONSTRAINT CONSTRAINT_INDEX_1 PRIMARY KEY ("icd_code")
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_1 ON PUBLIC."icd" (icd_id) ;

CREATE TABLE PUBLIC."icd10uatree" (
	"icd10uatree_id" INTEGER NOT NULL,
	"icd10uatree_parent_id" INTEGER NOT NULL,
	CONSTRAINT CONSTRAINT_F PRIMARY KEY ("icd10uatree_id"),
	CONSTRAINT CONSTRAINT_F6 FOREIGN KEY ("icd10uatree_id") REFERENCES PUBLIC."icd"("icd_id") ON DELETE RESTRICT ON UPDATE RESTRICT
) ;
CREATE UNIQUE INDEX PRIMARY_KEY_F ON PUBLIC."icd10uatree" (icd10uatree_id) ;

